version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - db
  
  db:
    image: postgres:14-alpine
    volumes:
      - ./tmp/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
